<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="test.LoginTest" duration-ms="20434" started-at="2020-12-29T05:35:13Z" finished-at="2020-12-29T05:35:33Z">
    <groups>
    </groups>
    <test name="Command line test" duration-ms="20434" started-at="2020-12-29T05:35:13Z" finished-at="2020-12-29T05:35:33Z">
      <class name="test.LoginTest">
        <test-method status="PASS" signature="launchBrowser()[pri:0, instance:test.LoginTest@3796751b]" name="launchBrowser" is-config="true" duration-ms="5980" started-at="2020-12-29T05:35:13Z" finished-at="2020-12-29T05:35:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method status="PASS" signature="validUserShouldBeAbleToLogin()[pri:1, instance:test.LoginTest@3796751b]" name="validUserShouldBeAbleToLogin" duration-ms="4796" started-at="2020-12-29T05:35:19Z" finished-at="2020-12-29T05:35:24Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validUserShouldBeAbleToLogin -->
        <test-method status="PASS" signature="close()[pri:0, instance:test.LoginTest@3796751b]" name="close" is-config="true" duration-ms="725" started-at="2020-12-29T05:35:24Z" finished-at="2020-12-29T05:35:24Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close -->
        <test-method status="PASS" signature="launchBrowser()[pri:0, instance:test.LoginTest@3796751b]" name="launchBrowser" is-config="true" duration-ms="3528" started-at="2020-12-29T05:35:24Z" finished-at="2020-12-29T05:35:28Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method status="FAIL" signature="invalidUserShouldBeAbleToLogin()[pri:2, instance:test.LoginTest@3796751b]" name="invalidUserShouldBeAbleToLogin" duration-ms="4648" started-at="2020-12-29T05:35:28Z" finished-at="2020-12-29T05:35:33Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Invalid User was able to login!! expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Invalid User was able to login!! expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertFalse(Assert.java:65)
at test.LoginTest.invalidUserShouldBeAbleToLogin(LoginTest.java:67)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:110)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- invalidUserShouldBeAbleToLogin -->
        <test-method status="PASS" signature="close()[pri:0, instance:test.LoginTest@3796751b]" name="close" is-config="true" duration-ms="714" started-at="2020-12-29T05:35:33Z" finished-at="2020-12-29T05:35:33Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close -->
      </class> <!-- test.LoginTest -->
    </test> <!-- Command line test -->
  </suite> <!-- test.LoginTest -->
</testng-results>
